name: 🔬 Tests and coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run Tests with Coverage
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[testing]

      - name: Run Pytest with coverage
        run: |
          pytest --cov=lite_media_core --cov-append --cov-report=term ./tests
          cp .coverage .coverage.regular

      - name: Install dependencies (embedded)
        if: false  # Experimental, disable the step this is still WIP
        run: |
          pip install .[embedded]

      - name: Run Pytest with coverage (embedded)
        if: false  # Experimental, disable the step this is still WIP
        run: |
          pytest --cov=lite_media_core --cov-append --cov-report=term ./tests_embedded
          cp .coverage .coverage.embedded

      - name: Combine coverage
        run: |
          pip install coverage
          coverage combine
          coverage xml

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
